version: "3.7"

services:
  api:
    build:
      context: .
    volumes:
      - ./:/app/
    working_dir: /app
    command: sh init.sh
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql